# #############################################################################
# -----------------------------------------------------------------------------
# File:   conda.yaml
# Author: Luis Monteiro
#
# Created on nov 17, 2019, 22:00 PM
# -----------------------------------------------------------------------------
# #############################################################################
package:
  name: space-vision
# -----------------------------------------------------------------------------
# SOURCE
# -----------------------------------------------------------------------------
source:
  path: ./
# -----------------------------------------------------------------------------
# BUILD
# -----------------------------------------------------------------------------
build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . 
# -----------------------------------------------------------------------------
# REQUIREMENTS
# -----------------------------------------------------------------------------
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytesseract

# -----------------------------------------------------------------------------
# ABOUT
# -----------------------------------------------------------------------------
about:
  home: ''
  license: ''
  license_file: LICENSE
  summary: ''
# #############################################################################
# -----------------------------------------------------------------------------
# END
# -----------------------------------------------------------------------------
# #############################################################################