# #############################################################################
# -----------------------------------------------------------------------------
# File:   meta.yaml
# Author: Luis Monteiro
#
# Created on nov 17, 2019, 22:00 PM
# -----------------------------------------------------------------------------
# #############################################################################
# -----------------------------------------------------------------------------
# package
# -----------------------------------------------------------------------------
package:
  name: space-vision

# -----------------------------------------------------------------------------
# source
# -----------------------------------------------------------------------------
source:
  path: ../

# -----------------------------------------------------------------------------
# build
# -----------------------------------------------------------------------------
build:
  number: 0
  #noarch: python
  script: python -m pip install --no-deps .
  entry_points:
    - vision-robot= vision.bindings.robotframework:main

# -----------------------------------------------------------------------------
# requirements
# -----------------------------------------------------------------------------
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytesseract [conda-forge]

# -----------------------------------------------------------------------------
# test
# -----------------------------------------------------------------------------
test:
  imports:
    - vision

# -----------------------------------------------------------------------------
# about
# -----------------------------------------------------------------------------
about:
  home: https://github.com/lcmonteiro/space-vision-py
  license: MIT
  license_file: LICENSE
# #############################################################################
# -----------------------------------------------------------------------------
# end
# -----------------------------------------------------------------------------
# #############################################################################