# #############################################################################
# -----------------------------------------------------------------------------
# File:   enviroment.yaml
# Author: Luis Monteiro
#
# Created on nov 17, 2019, 22:00 PM
# -----------------------------------------------------------------------------
# #############################################################################
# -----------------------------------------------------------------------------
# properties 
# -----------------------------------------------------------------------------
name: space-vision

channels:
  - conda-forge
  - default

dependencies:
  - python >=3.6
  - pytesseract
# #############################################################################
# -----------------------------------------------------------------------------
# end
# -----------------------------------------------------------------------------
# #############################################################################